"""persistent workers and login limits

Revision ID: c060c2b494d8
Revises: 1ba017089746
"""
from alembic import op
import sqlalchemy as sa


revision = 'c060c2b494d8'
down_revision = '1ba017089746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_key_hash'), 'login_attempts', ['key_hash'], unique=False)
    op.create_index(op.f('ix_login_attempts_occurred_at'), 'login_attempts', ['occurred_at'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('worker', sa.String(length=50), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('worker')
    )
    op.create_index(op.f('ix_worker_heartbeats_last_seen_at'), 'worker_heartbeats', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_heartbeats_last_seen_at'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_login_attempts_occurred_at'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_key_hash'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
